import { NextResponse, type NextRequest } from 'next/server';
import { writeFile } from 'fs/promises';
import { existsSync } from 'fs';
import { join } from 'path';
import { getAmiClient } from '@/lib/asterisk/ami-client';
import { connectDb } from '@/lib/db/connection';
import { InboundRoute } from '@/lib/db/models/InboundRoute';
import { IvrFlow } from '@/lib/db/models/IvrFlow';
import { AsteriskSettings } from '@/lib/db/models/AsteriskSettings';
import { withUser } from '@/lib/auth/rbac';
import type { JwtPayload } from '@/lib/auth/jwt';

function generateDialplanFragment(
  routes: Array<{ did: string; destination: string; destinationId?: string; destinationName?: string }>,
): string {
  const lines = [
    '; ============================================================',
    '; Auto-generated by DialerOS — do not edit manually',
    '; Push via: Dashboard → Inbound Routes → Push to Asterisk',
    '; ============================================================',
    '',
    '[from-trunk]',
  ];
  for (const r of routes) {
    if (!r.did) continue;
    if (r.destination === 'hangup') {
      lines.push(`exten => ${r.did},1,Hangup()`);
      lines.push('');
      continue;
    }
    lines.push(`exten => ${r.did},1,NoOp(DialerOS Inbound: DID=${r.did} Dest=${r.destination})`);
    switch (r.destination) {
      case 'ivr_flow':
        lines.push(`exten => ${r.did},n,Goto(ivr-${r.destinationId ?? 'default'},s,1)`);
        break;
      case 'queue':
        lines.push(`exten => ${r.did},n,Answer()`);
        lines.push(`exten => ${r.did},n,Queue(${r.destinationId},t,,,300)`);
        break;
      case 'extension':
        lines.push(`exten => ${r.did},n,Dial(PJSIP/${r.destinationId},30,tT)`);
        break;
      case 'voicemail':
        lines.push(`exten => ${r.did},n,Answer()`);
        lines.push(`exten => ${r.did},n,VoiceMail(${r.destinationId}@default,u)`);
        break;
      case 'announcement':
        lines.push(`exten => ${r.did},n,Answer()`);
        lines.push(`exten => ${r.did},n,Playback(${r.destinationId ?? 'vm-sorry'})`);
        break;
    }
    lines.push(`exten => ${r.did},n,Hangup()`);
    lines.push('');
  }
  return lines.join('\n');
}

export const GET = withUser(async (_req: NextRequest, _user: JwtPayload) => {
  await connectDb();
  const routes = await InboundRoute.find({}).sort({ priority: 1 }).lean();
  return NextResponse.json({ data: routes });
});

export const POST = withUser(async (req: NextRequest, _user: JwtPayload) => {
  await connectDb();
  const body = await req.json() as {
    did: string; description?: string; destination: string;
    destinationId?: string; priority?: number;
    autoPush?: boolean;  // default true — push to Asterisk immediately
  };

  if (!body.did) return NextResponse.json({ error: 'did is required' }, { status: 400 });

  let destinationName: string | undefined;
  if (body.destination === 'ivr_flow' && body.destinationId) {
    const flow = await IvrFlow.findById(body.destinationId).select('name').lean();
    destinationName = flow?.name;
  }

  const route = await InboundRoute.create({ ...body, destinationName });

  // Auto-push dialplan to Asterisk unless caller explicitly opts out
  const autoPush = body.autoPush !== false;
  let pushResult: { fileWritten: boolean; reloaded: boolean; error?: string } | null = null;

  if (autoPush) {
    try {
      const allRoutes = await InboundRoute.find({ isActive: true }).sort({ priority: 1 }).lean();
      const dialplan = generateDialplanFragment(allRoutes);
      const ASTERISK_CONF_DIR = process.env.ASTERISK_CONF_DIR ?? '/etc/asterisk';
      const confPath = join(ASTERISK_CONF_DIR, 'extensions_dialer.conf');
      let fileWritten = false;
      if (existsSync(ASTERISK_CONF_DIR)) {
        try { await writeFile(confPath, dialplan, 'utf8'); fileWritten = true; } catch { /* permission denied */ }
      }
      let reloaded = false;
      let reloadError: string | undefined;
      try {
        const ami = await getAmiClient();
        await ami.sendAction({ Action: 'Command', Command: 'dialplan reload' });
        reloaded = true;
        await InboundRoute.updateMany({ isActive: true }, { lastPushed: new Date() });
      } catch (e) { reloadError = String(e); }
      pushResult = { fileWritten, reloaded, ...(reloadError ? { error: reloadError } : {}) };
    } catch (e) {
      pushResult = { fileWritten: false, reloaded: false, error: String(e) };
    }
  }

  return NextResponse.json({ data: route, push: pushResult }, { status: 201 });
});


export const PUT = withUser(async (req: NextRequest, _user: JwtPayload) => {
  const { action } = await req.json() as { action: string };
  if (action !== 'push_dialplan') return NextResponse.json({ error: 'Unknown action' }, { status: 400 });

  await connectDb();
  const routes = await InboundRoute.find({ isActive: true }).sort({ priority: 1 }).lean();
  const dialplan = generateDialplanFragment(routes);

  // Try to write the file directly to the Asterisk config directory
  const ASTERISK_CONF_DIR = process.env.ASTERISK_CONF_DIR ?? '/etc/asterisk';
  const confPath = join(ASTERISK_CONF_DIR, 'extensions_dialer.conf');
  let fileWritten = false;

  if (existsSync(ASTERISK_CONF_DIR)) {
    try {
      await writeFile(confPath, dialplan, 'utf8');
      fileWritten = true;
    } catch (writeErr) {
      // Permission denied — fall through to AMI reload + return dialplan for manual copy
      console.warn('[inbound] Could not write dialplan file directly:', writeErr);
    }
  }

  // Reload dialplan via AMI (works whether or not we wrote the file)
  let reloaded = false;
  let reloadError: string | undefined;
  try {
    const ami = await getAmiClient();
    await ami.sendAction({ Action: 'Command', Command: 'dialplan reload' });
    reloaded = true;
    await InboundRoute.updateMany({ isActive: true }, { lastPushed: new Date() });
  } catch (err) {
    reloadError = String(err);
  }

  return NextResponse.json({
    ok: reloaded,
    fileWritten,
    reloaded,
    error: reloadError,
    // Always return the dialplan text so user can copy it manually if needed
    dialplan,
    manualPath: confPath,
  });
});
