'use client';

import { useEffect, useState } from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { RefreshCw, Loader2, Send, Map } from 'lucide-react';
import { cn } from '@/lib/utils';

interface DialplanCtx { context: string; count: number }

const DIALER_TEMPLATES = [
  {
    id: 'agents',
    label: 'Agents Context',
    description: 'Handles the agent leg — recording, whisper prompts.',
    dialplan: `[agents]
exten => _X.,1,NoOp(Agent call: \${EXTEN})
exten => _X.,n,Answer()
exten => _X.,n,MixMonitor(\${STRFTIME(\${EPOCH},,\%Y\%m\%d-\%H\%M\%S)}-\${CALLERID(num)}-\${EXTEN}.wav,ab)
exten => _X.,n,Dial(PJSIP/\${EXTEN},30,tT)
exten => _X.,n,Hangup()`,
  },
  {
    id: 'from-trunk',
    label: 'From-Trunk (Inbound)',
    description: 'Entry point for all calls from your SIP provider. Routes to IVR/queue based on DID.',
    dialplan: `[from-trunk]
; Auto-generated by DialerOS — push inbound routes from the Inbound Routes page
exten => _X.,1,NoOp(Inbound: \${EXTEN} from \${CALLERID(num)})
exten => _X.,n,Hangup()`,
  },
  {
    id: 'dialer-outbound',
    label: 'Dialer Outbound',
    description: 'Used by the worker to originate predictive calls via your SIP trunk.',
    dialplan: `[dialer-outbound]
; Called by the dialer worker via ARI Originate
exten => _X.,1,NoOp(Outbound dialer call to \${EXTEN})
exten => _X.,n,Answer()
exten => _X.,n,AGI(agi:async)
exten => _X.,n,Hangup()`,
  },
];

export default function DialplanPage() {
  const [contexts, setContexts] = useState<DialplanCtx[]>([]);
  const [loading, setLoading] = useState(true);
  const [reloading, setReloading] = useState(false);
  const [reloadResult, setReloadResult] = useState('');
  const [error, setError] = useState('');
  const [copied, setCopied] = useState('');

  const token = () => localStorage.getItem('access_token') ?? '';
  const h = () => ({ Authorization: `Bearer ${token()}`, 'Content-Type': 'application/json' });

  const load = () => {
    setLoading(true);
    // Parse contexts from AMI command output
    fetch('/api/asterisk/ami', {
      method: 'POST', headers: h(),
      body: JSON.stringify({ action: 'Command', fields: { Command: 'dialplan show' } }),
    }).then(r => r.json()).then((d: { ok: boolean; data: { Output?: string } }) => {
      if (!d.ok) { setError('Could not reach Asterisk'); return; }
      const output = d.data?.Output ?? '';
      const hits = [...output.matchAll(/^Context\s+'(\S+?)'\s+\((\d+)/gm)];
      setContexts(hits.map(m => ({ context: m[1] ?? '', count: parseInt(m[2] ?? '0', 10) })));
    }).finally(() => setLoading(false));
  };
  useEffect(load, []);

  const reload = async () => {
    setReloading(true); setReloadResult('');
    const r = await fetch('/api/asterisk/system', { method: 'POST', headers: h(), body: JSON.stringify({ action: 'reload_dialplan' }) });
    const d = await r.json() as { ok: boolean; output?: string; error?: string };
    setReloadResult(d.ok ? '✅ Dialplan reloaded successfully' : `❌ ${d.error ?? 'Failed'}`);
    setReloading(false);
    load();
  };

  const copy = (id: string, text: string) => {
    void navigator.clipboard.writeText(text);
    setCopied(id);
    setTimeout(() => setCopied(''), 2000);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div><h1 className="text-2xl font-bold">Dialplan Manager</h1>
          <p className="text-sm text-muted-foreground mt-1">View active contexts and reload — use Inbound Routes to push DID routing</p></div>
        <div className="flex gap-2">
          <Button variant="secondary" size="sm" onClick={load}><RefreshCw className="h-4 w-4" /></Button>
          <Button size="sm" onClick={() => void reload()} disabled={reloading}>
            {reloading ? <><Loader2 className="h-4 w-4 animate-spin" /> Reloading…</> : <><Send className="h-4 w-4" /> Reload Dialplan</>}
          </Button>
        </div>
      </div>

      {error && <div className="rounded-lg border border-destructive/50 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</div>}
      {reloadResult && <div className={cn('rounded-lg border px-4 py-3 text-sm', reloadResult.startsWith('✅') ? 'border-success/30 bg-success/10 text-success' : 'border-destructive/30 bg-destructive/10 text-destructive')}>{reloadResult}</div>}

      {/* Active contexts */}
      <Card>
        <CardContent className="pt-4">
          <p className="text-sm font-medium mb-3 flex items-center gap-2"><Map className="h-4 w-4" /> Active Contexts ({contexts.length})</p>
          {loading ? <div className="py-6 text-center text-sm text-muted-foreground">Loading dialplan from Asterisk…</div> : (
            <div className="flex flex-wrap gap-2">
              {contexts.map(c => (
                <Badge key={c.context} variant="secondary" className="font-mono text-xs">
                  {c.context} <span className="text-muted-foreground ml-1">({c.count} ext)</span>
                </Badge>
              ))}
              {contexts.length === 0 && <p className="text-sm text-muted-foreground">No contexts visible — check Asterisk connection.</p>}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Template library */}
      <p className="text-sm font-medium">Dialplan Templates</p>
      <p className="text-xs text-muted-foreground -mt-4">Copy these into your <code className="font-mono bg-secondary px-1 rounded">extensions_dialer.conf</code> (included from <code className="font-mono bg-secondary px-1 rounded">extensions.conf</code>) then click <strong>Reload Dialplan</strong>.</p>

      <div className="space-y-4">
        {DIALER_TEMPLATES.map(t => (
          <Card key={t.id}>
            <CardContent className="pt-4 space-y-2">
              <div className="flex items-start justify-between gap-3">
                <div>
                  <p className="font-medium text-sm">{t.label}</p>
                  <p className="text-xs text-muted-foreground">{t.description}</p>
                </div>
                <Button size="sm" variant="secondary" onClick={() => copy(t.id, t.dialplan)}>
                  {copied === t.id ? '✓ Copied' : 'Copy'}
                </Button>
              </div>
              <pre className="text-xs font-mono bg-secondary rounded-lg p-4 overflow-x-auto whitespace-pre">{t.dialplan}</pre>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
