/**
 * Dialer Worker
 *
 * Fixes applied:
 *   ISSUE-01: Stall handler releases concurrency slot + decrements stats.active
 *   ISSUE-02: Concurrency limit stored IN Redis so replicas share single truth
 *   ISSUE-05: Uses canonical @dialer/db models (no inline schema)
 *   ISSUE-08: moveToDelayed + throw DelayedError (prevents silent job loss)
 *   ISSUE-13: Duplicate channelId key error handled explicitly
 *   ISSUE-25: stats.active clamped at 0 via aggregation pipeline
 */

import {
  Worker,
  Job,
  type WorkerOptions,
  UnrecoverableError,
  DelayedError,
} from 'bullmq';
import type { Redis } from 'ioredis';
import { v4 as uuidv4 } from 'uuid';
import {
  QUEUE_NAMES,
  JOB_NAMES,
  REDIS_KEYS,
  type DialJobPayload,
} from '@dialer/shared';
import { CallLog, Contact, Campaign } from '@dialer/db';
import { AriClient } from '../services/ariClient.js';
import { DncService } from '../services/dncService.js';
import { ConcurrencyManager } from '../services/concurrencyManager.js';
import { ErlangCPacingService } from '../services/pacingService.js';
import { logger } from '../lib/logger.js';

/** Atomically clamp stats.active at 0 — prevents negative values (ISSUE-25) */
async function decrementActiveClamp(campaignId: string): Promise<void> {
  await Campaign.updateOne(
    { _id: campaignId },
    [{ $set: { 'stats.active': { $max: [{ $subtract: ['$stats.active', 1] }, 0] } } }],
  );
}

export function createDialerWorker(redis: Redis): Worker {
  const ari = new AriClient();
  const dnc = new DncService(redis);
  const concurrency = new ConcurrencyManager(redis);
  const pacing = new ErlangCPacingService(redis);

  const workerOptions: WorkerOptions = {
    connection: redis,
    concurrency: parseInt(process.env['WORKER_CONCURRENCY'] ?? '10', 10),
    limiter: {
      max: parseInt(process.env['WORKER_RATE_LIMIT_MAX'] ?? '10', 10),
      duration: parseInt(process.env['WORKER_RATE_LIMIT_DURATION'] ?? '1000', 10),
    },
  };

  const worker = new Worker<DialJobPayload>(
    QUEUE_NAMES.DIALER_CALLS,
    async (job: Job<DialJobPayload>) => {
      const {
        contactId, campaignId, phone, callerIdName, callerIdNumber,
        sipTrunk, concurrencyLimit, amdAction, ivrFlowId, attempt,
      } = job.data;

      const jobLog = logger.child({ jobId: job.id, contactId, campaignId, phone, attempt });
      jobLog.info('Dialer job started');

      // 1. DNC check
      const isBlocked = await dnc.isBlocked(phone);
      if (isBlocked) {
        jobLog.info('Contact on DNC — skipping');
        await Contact.updateOne({ _id: contactId }, { $set: { status: 'dnc' } });
        return;
      }

      // 2. Store concurrency limit in Redis (ISSUE-02: single authoritative value for all replicas)
      await redis.set(`campaign:limit:${campaignId}`, String(concurrencyLimit), 'EX', 86400);

      // 3. Concurrency check
      const acquired = await concurrency.tryAcquire(campaignId);
      if (!acquired) {
        jobLog.debug('Concurrency limit reached — requeueing with delay');
        // ISSUE-08: must throw DelayedError after moveToDelayed
        await job.moveToDelayed(Date.now() + 2000, job.token);
        throw new DelayedError();
      }

      // 4. Create pre-flight call log
      const channelId = `dialer-${uuidv4()}`;
      let callLog;
      try {
        callLog = await CallLog.create({
          contactId,
          campaignId,
          channelId,
          asteriskCallerId: callerIdNumber,
          startTime: new Date(),
          disposition: 'no_answer',
          attempt,
          retryable: true,
        });
      } catch (err: unknown) {
        // ISSUE-13: handle duplicate channelId (should never happen with UUID but be safe)
        if ((err as { code?: number }).code === 11000) {
          await concurrency.release(campaignId);
          throw new UnrecoverableError('Duplicate channelId — UUID collision (fatal)');
        }
        await concurrency.release(campaignId);
        throw err;
      }

      await Contact.updateOne({ _id: contactId }, { $set: { status: 'dialing' }, $push: { callLogs: callLog._id } });
      await Campaign.updateOne({ _id: campaignId }, { $inc: { 'stats.active': 1, 'stats.dialed': 1 } });

      // 5. Originate call
      try {
        await ari.originateCall({
          endpoint: `${sipTrunk}/${phone}`,
          app: process.env['ARI_APP_NAME'] ?? 'dialer',
          appArgs: [campaignId, contactId, String(callLog._id)].join(','),
          callerId: `"${callerIdName}" <${callerIdNumber}>`,
          timeout: 30,
          channelId,            // always a string (generated by uuidv4 above)
          variables: {          // always an object
            DIALER_CAMPAIGN_ID: campaignId,
            DIALER_CONTACT_ID: contactId,
            DIALER_CALLLOG_ID: String(callLog._id),
            DIALER_AMD_ACTION: amdAction,
            DIALER_IVR_FLOW_ID: ivrFlowId ?? '',
            DIALER_ATTEMPT: String(attempt),
          },
        });

        // Store channel context — includes channelId so stall watchdog can find it (ISSUE-01)
        await redis.setex(
          REDIS_KEYS.CHANNEL_CONTEXT(channelId),
          3600,
          JSON.stringify({ callLogId: String(callLog._id), contactId, campaignId, amdAction, ivrFlowId, channelId }),
        );

        await pacing.recordDialAttempt(campaignId, false);
        jobLog.info({ channelId }, 'Call originated successfully');
      } catch (err) {
        // Originate failed — release slot immediately
        await concurrency.release(campaignId);
        await decrementActiveClamp(campaignId);
        await CallLog.updateOne({ _id: callLog._id }, { $set: { disposition: 'failed', endTime: new Date(), retryable: true } });
        await Contact.updateOne({ _id: contactId }, { $set: { status: 'failed' } });
        jobLog.error({ err }, 'ARI originate failed');
        throw new Error(`Originate failed: ${String(err)}`);
      }
    },
    workerOptions,
  );

  // ISSUE-01: stall handler releases the concurrency slot to prevent permanent freezes
  worker.on('stalled', (jobId) => {
    logger.warn({ jobId }, 'Job stalled — attempting slot recovery');
    void (async () => {
      try {
        const job = await Job.fromId<DialJobPayload>(worker, jobId);
        if (job?.data?.campaignId) {
          await concurrency.release(job.data.campaignId);
          await decrementActiveClamp(job.data.campaignId);
          logger.warn({ jobId, campaignId: job.data.campaignId }, 'Stall: concurrency slot recovered');
        }
      } catch (e) {
        logger.error({ e, jobId }, 'Failed to recover stalled job concurrency slot');
      }
    })();
  });

  worker.on('completed', (job) => logger.info({ jobId: job.id }, 'Dialer job completed'));
  worker.on('failed', (job, err) => logger.error({ jobId: job?.id, err: err.message }, 'Dialer job failed'));
  worker.on('error', (err) => logger.error({ err }, 'Dialer worker error'));

  return worker;
}
